#!/bin/bash
  
#SBATCH -p compute       # which partition to run on
#SBATCH -J ez-cache    # name for the job
#SBATCH --mem=
#SBATCH --cpus-per-task=16
#SBATCH --ntasks=1
#SBATCH -N 1-1

source ${HOME}/tri-training/mtb-tri-training/config/locations.sh

SCRIPTDIR=${PRJ_DIR}/scripts

# export TT_DEBUG=1

STOPFILE=${HOME}/tri-training/stop-elmo-npz-cache

rm -f $STOPFILE

cd ${SCRIPTDIR}

python3 ./elmo_udpf.py   \
    --deadline 27.0       \
    --stopfile $STOPFILE   \
    elmo-npz

